name: Deploy to cPanel

on:
  push:
    branches:
      - development

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to cPanel
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: ftp.armgp.org  # ${{ secrets.FTP_SERVER }}
        username: userarmgp # ${{ secrets.FTP_USERNAME }}
        password: TGA&7f&a.@y.wF@*#] # ${{ secrets.FTP_PASSWORD }}
        port: 22
        protocol: ftps
        # local-dir: ./ # Directorio local a subir
        server-dir: /public_html/dev/ # Directorio en el servidor cPanel
        exclude: |
          **/.git*
          **/.git*/**
